### ISSUE TITLE
Is there a way to run code in case if all retries are exhausted?

### ISSUE THREAD

**Issue by Hirurg103** [isaacseymour/activejob-retry#46]
I want to call our error notifier in case when all retries are exhausted

Like this way:
```ruby
class ProcessWebhook < ActiveJob::Base
  include ActiveJob::Retry.new(
    strategy: :constant,
    limit: 3,
    delay: 5.minutes,
    retries_exhausted: -> (error) { Notifier.call(error.message) } # <--- note this line
  )
  # ...
end
```
Or this:
```ruby
class ProcessWebhook < ActiveJob::Base
  # ...

  def perform
     begin
       # do work
     rescue => e
       if retry_rumber == MaxRetries
          Notifier.call(e.message)
       else
         raise
       end
     end
   end
end
```

Is there a way to run code when retry limit is reached?

**Comment by isaacseymour** [comment]
Hi @Hirurg103 - I think you can just use the normal ActiveJob error handling for this (`rescue_from`).

**Comment by Hirurg103** [comment]
Hi @isaacseymour , thank you!

**Comment by fguillen** [comment]
Hi @isaacseymour we are here with the same need as @Hirurg103 described in the initial post. I don't understand the solution you are proposing about using `rescue_from`.  

In our case we want to send an specific error in case the retries have been exhausted. We don't want to send the error on each specific retry.

Is there any mechanism we can use to detect when all the retries have been exhausted?

**Comment by isaacseymour** [comment]
@fguillen the way this library works is to intercept `rescue_from`, and instead retry the job (_without_ calling the `rescue_from` block) if the criteria are met.

Therefore, you can use the `rescue_from` block to handle the case where retries have been exhausted.

E.g.
```ruby

class MyJob < ActiveJob::Base
  MyError = Class.new(StandardError)

  include ActiveJob::Retry.new(strategy: :constant, limit: 2, retryable_exceptions: [MyError], ...)

  rescue_from(MyError) do |ex|
    puts ex.inspect
  end

  def perform
    raise MyError
  end
end
```

This job will:
- run first time, raise `MyError` -> `ActiveJob::Retry` retries because it's been attempted once (<2)
- run second time - it's now at the limit of retries. So `ActiveJob::Retry` gets out the way and lets ActiveJob handle the error - so the `rescue_from` block gets called and prints out the exception.

Does that make sense?

**Comment by fguillen** [comment]
Thanks @isaacseymour it has a lot of sense!
